package com;
// Generated Feb 4, 2017 2:19:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer eid;
     private String name;
     private String eimage;
     private Date etime;

    public Event() {
    }

    public Event(String name, String eimage, Date etime) {
       this.name = name;
       this.eimage = eimage;
       this.etime = etime;
    }
   
    public Integer getEid() {
        return this.eid;
    }
    
    public void setEid(Integer eid) {
        this.eid = eid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEimage() {
        return this.eimage;
    }
    
    public void setEimage(String eimage) {
        this.eimage = eimage;
    }
    public Date getEtime() {
        return this.etime;
    }
    
    public void setEtime(Date etime) {
        this.etime = etime;
    }




}


