package com;
// Generated Feb 4, 2017 2:19:42 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int rollnumber;
     private String name;
     private String email;
     private String password;
     private String phone;
     private String branch;
     private String type;

    public Login() {
    }

    public Login(int rollnumber, String name, String email, String password, String phone, String branch, String type) {
       this.rollnumber = rollnumber;
       this.name = name;
       this.email = email;
       this.password = password;
       this.phone = phone;
       this.branch = branch;
       this.type = type;
    }
   
    public int getRollnumber() {
        return this.rollnumber;
    }
    
    public void setRollnumber(int rollnumber) {
        this.rollnumber = rollnumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


