package com;
// Generated Feb 4, 2017 2:19:42 PM by Hibernate Tools 4.3.1



/**
 * Qbank generated by hbm2java
 */
public class Qbank  implements java.io.Serializable {


     private Integer qeid;
     private String cname;
     private String set;

    public Qbank() {
    }

    public Qbank(String cname, String set) {
       this.cname = cname;
       this.set = set;
    }
   
    public Integer getQeid() {
        return this.qeid;
    }
    
    public void setQeid(Integer qeid) {
        this.qeid = qeid;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getSet() {
        return this.set;
    }
    
    public void setSet(String set) {
        this.set = set;
    }




}


