package com;
// Generated Feb 4, 2017 2:19:42 PM by Hibernate Tools 4.3.1



/**
 * Sharecodes generated by hbm2java
 */
public class Sharecodes  implements java.io.Serializable {


     private Integer sid;
     private String key;

    public Sharecodes() {
    }

    public Sharecodes(String key) {
       this.key = key;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }




}


